DROP DATABASE IF EXISTS avatar_db;

CREATE DATABASE avatar_db;

\c avatar_db;

CREATE TABLE users (
    id SERIAL PRIMARY KEY,
    username VARCHAR(300) UNIQUE NOT NULL,
    password VARCHAR(300) NOT NULL,
    email VARCHAR(300) UNIQUE NOT NULL,
    favorite_character VARCHAR(300)
);

CREATE TABLE characters (
    id SERIAL PRIMARY KEY,
    name TEXT NOT NULL,
    image TEXT NOT NULL,
    bio_nationality TEXT DEFAULT 'Unknown',
    bio_ethnicity TEXT DEFAULT 'Unknown',
    bio_ages TEXT[] DEFAULT '{}',
    physical_description_gender TEXT DEFAULT 'Unknown',
    personal_information_allies TEXT[] DEFAULT '{}',
    personal_information_enemies TEXT[] DEFAULT '{}',
    personal_information_weapons_of_choice TEXT[] DEFAULT '{}',
    personal_information_fighting_styles TEXT[] DEFAULT '{}'
);

INSERT INTO characters (name, image, bio_nationality, bio_ethnicity, bio_ages, physical_description_gender, personal_information_allies, personal_information_enemies, personal_information_weapons_of_choice, personal_information_fighting_styles)
VALUES
    ('Aang', 'https://static.wikia.nocookie.net/avatar/images/a/ae/Aang_at_Jasmine_Dragon.png', 'Southern Air Temple', 'Air Nomad', '{"112 (biologically 12) in Avatar: The Last Airbender[3]","113-114 (biologically 13-14) in The Promise trilogy[4]","114-115 (biologically 14-15) in The Search and The Rift trilogies[5]","165 (biologically 66) at death[6]"}', 'Male', '{"Appa","Katara","Momo","Sokka","Tenzin","Toph","Zuko","King Bumi","Bumi","Gyatso","Hakoda","Iroh","Kya","Suki","Kuzon","lion turtle","all Avatars"}', '{"Azula","Ozai","Zhao","Zuko (formerly)","Combustion Man","Long Feng","Sozin","Yakone","Joo Dee","the Dai Li"}', '{"The elements","glider staff"}', '{"Airbending","waterbending (Northern and Southern style)","earthbending (Chu Gar Praying Mantis Kung Fu)","firebending (Dancing Dragon)","energybending"}'),
    ('Appa', 'https://static.wikia.nocookie.net/avatar/images/6/65/Appa_flying.png', 'Air Nomad', NULL, NULL, 'Male', '{"Azula","Ozai","Zuko (formerly)","Combustion Man","Zhao","Long Feng","the Dai Li","Shuzumu","circus trainer","Ghashiun","Si Wong tribes","beetle-headed merchants"}', '{"Air","body bulk","tail"}', '{"Airbending"}', NULL),
    ('Momo', 'https://static.wikia.nocookie.net/avatar/images/8/80/Momo_staring.png', 'Air Nomad', NULL, NULL, 'Male', '{"Ozai","Azula","Zhao","Zuko (formerly)","Long Feng","the Dai Li","Tom-Tom","Fire Nation (formerly)","buzzard wasp","Hawky","iguana parrot","bearded cat"}', NULL, NULL, NULL),
    ('Katara', 'https://static.wikia.nocookie.net/avatar/images/7/7a/Katara_smiles_at_coronation.png', 'Southern Water Tribe capital city, Southern Water Tribe', 'Water Tribe', '{"14 in Avatar: The Last Airbender[3]","15-16 in The Promise trilogy[4]","16-17 in The Search and The Rift trilogies[5]","85 in Book One: Air of The Legend of Korra[6]","86 in Book Two: Spirits","89 in Book Four: Balance[7]"}', 'Female', '{"Yue","the Painted Lady","Hakoda","Kya","Kanna","Tenzin","Bumi","Kya","Jinora","Ikki","Meelo","Rohan","Team Avatar","Order of the White Lotus","Air Acolytes","Hama (formerly)","Yagoda","Malina","Maliq (formerly)","Korra","Niyok","Nutha","Siku and Sura","Rafa and Misu","Ashuna","Kyoshi Warriors","Mai","Tyro"}', '{"Mother of Faces (formerly)","Wan Shi Tong","Old Iron","Ozai","Azula","Zuko (formerly)","Azula''s team (formerly)","Zhao","Combustion Man","Rough Rhinos","Fire Nation (formerly)","Long Feng","the Dai Li","Azulon","Yon Rha","the Southern Raiders","Hama","Gilak","Thod and his disciples","Southern Water Tribe nationalists","Maliq and Malina''s workers"}', '{"Water"}', '{"Waterbending (Northern and Southern styles)","bloodbending (resigned from use)"}'),
    ('Sokka', 'https://static.wikia.nocookie.net/avatar/images/c/cc/Sokka.png', 'Southern Water Tribe capital city, Southern Water Tribe', 'Water Tribe', '{"15 in Avatar: The Last Airbender[3]","16-17 in The Promise trilogy[4]","17-18 in The Search and The Rift trilogies[5]","44 in The Legend of Korra (flashback to Yakone''s trial)"}', 'Male', '{"Hakoda","Kya","Kanna","Katara","Pakku","Aang","Toph","Zuko","Suki","Appa","Momo","Hawky","Piandao","Yue","Order of the White Lotus","Southern Water Tribe","United Republic Council","Tonraq","Tenzin","Korra"}', '{"Ozai","Azula","Zhao","Long Feng","Dai Li","Combustion Man","Southern Raiders","Azulon","Zuko (formerly)","Yon Rha","Hahn","Hama","Kunyo","Yakone","Fire Nation (formerly)","Red Lotus"}', '{"Sokka''s weapons (Jian","boomerang","club","machete","dagger","saber)"}', '{"Water Tribe Warrior style","tessenjutsu (basics)","swordsmanship (Jian-fencing)"}'),
    ('Toph Beifong', 'https://static.wikia.nocookie.net/avatar/images/4/46/Toph_Beifong.png', 'Gaoling, Earth Kingdom', 'Earth Kingdom', NULL, 'Female', '{"Aang","Katara","Sokka","Appa","Momo","Zuko","Suki","Metalbending Police Force","Iroh","Lin","Suyin","Order of the White Lotus","badgermoles","Team Beifong","Korra","Opal Beifong"}', '{"Ozai","Zuko (formerly)","Azula","Yakone","Long Feng","the Dai Li","Yu","Xin Fu","Combustion Man","Kunyo","Fire Nation (formerly)","Kuvira (formerly)","military of the Earth Empire"}', '{"Earth","metal"}', '{"Earthbending (Chu Gar Praying Mantis); metalbending"}'),
    ('Zuko', 'https://static.wikia.nocookie.net/avatar/images/4/4b/Zuko.png', 'Fire Nation Capital, Fire Nation', 'Fire Nation', '{"16 in Avatar: The Last Airbender[4]","17-18 in The Promise trilogy[5]","18-19 in The Search trilogy[6]","87-88 in Book Three: Change of The Legend of Korra[7]","90-91 in Book Four: Balance"}', 'Male', '{"Iroh","Ursa","Izumi","Noren","Aang","Appa","Azula (formerly)","Katara","Momo","Sokka","Suki","Toph","Ozai (formerly)","Hakoda","Mai","Ty Lee","General Iroh","Jin","June","Kiyi","Lu Ten","Fire Nation military","Kyoshi Warriors","Order of the White Lotus","Druk","Tonraq","Korra","Desna","Eska","Tenzin","Lin Beifong","Team Avatar"}', '{"Azula","Ozai","Azulon","Jet","Combustion Man","Zhao","Gow","the Rough Rhinos","Team Avatar (formerly)","Red Lotus","Earth Kingdom Army (formerly)","Ukano","New Ozai Society"}', '{"Fire","dual broadswords"}', '{"Firebending (Dancing Dragon)","dual dao swordsmanship"}'),
    ('Suki', 'https://static.wikia.nocookie.net/avatar/images/1/14/Suki.png', 'Earth Kingdom', NULL, NULL, 'Female', '{"Kyoshi Warriors","Oyaji","Sokka","Katara","Aang","Toph","Zuko","Appa","Momo","Mai","Ty Lee","Iroh","Order of the White Lotus"}', '{"Ozai","Azula","the warden","Fire Nation (formerly)","Zuko (formerly)","Ty Lee (formerly)"}', '{"War fans","katana"}', '{"Tessenjutsu","chi blocking"}'),
    ('Iroh', 'https://static.wikia.nocookie.net/avatar/images/c/c1/Iroh_smiling.png', 'Fire Nation Capital, Fire Nation', 'Fire Nation', NULL, 'Male', '{"Ozai","Azula","Zhao","Dai Li","Rough Rhinos","Fire Nation (formerly)"}', '{"Fire"}', '{"Firebending"}', NULL),
    ('Ozai', 'https://static.wikia.nocookie.net/avatar/images/4/4a/Ozai.png', 'Fire Nation', 'Fire Nation', '{"40s in Avatar: The Last Airbender[nb 1]"}', 'Male', '{"Fire Nation (formerly)","his loyalists","Azula","Zuko (formerly)","Fire Nation military (formerly)","Zhao","Ursa (formerly)","Ukano"}', '{"Team Avatar","Zuko","Iroh","Water Tribes","Earth Kingdom","Ursa","Ikem","Azulon"}', '{"Fire (formerly)","lightning (formerly)"}', '{"Firebending (formerly)","lightning generation (formerly)"}'),
    ('Azula', 'https://static.wikia.nocookie.net/avatar/images/1/12/Azula.png', 'Fire Nation', 'Fire Nation', '{"14 in Avatar: The Last Airbender[2]","15-16 in The Promise trilogy[3]","16-17 in The Search trilogy[4]"}', 'Female', '{"Ozai (formerly)","Zuko (formerly)","Mai (formerly)","Ty Lee (formerly)","Lo and Li (formerly)","Ursa","the Dai Li (formerly)","Fire Nation","Fire Nation military (formerly)","Fire Warriors"}', '{"Iroh","Zuko (formerly)","Kuei","Long Feng","Mai","Ty Lee","Ursa (formerly)","Earth Kingdom","Kyoshi Warriors","Team Avatar","Water Tribe"}', '{"Fire","lightning"}', '{"Firebending","lightning generation"}'),
    ('Zhao', 'https://static.wikia.nocookie.net/avatar/images/e/e1/Commander_Zhao.png', 'Fire Nation', 'Fog of Lost Souls, Spirit World', NULL, 'Male', '{"Aang","Katara","Iroh","Sokka","Zuko","Jeong Jeong","La","Tui","Yue","Wan Shi Tong","Water Tribes","Earth Kingdom"}', '{"Fire"}', '{"Firebending"}', NULL),
    ('Long Feng', 'https://static.wikia.nocookie.net/avatar/images/8/8d/Long_Feng_scheming.png', 'Earth Kingdom', NULL, NULL, 'Male', '{"Team Avatar","Azula","Jet","Kuei","Earth Kingdom","the Dai Li"}', '{"Earth"}', '{"Earthbending"}', NULL);

CREATE TABLE questions (
    id SERIAL PRIMARY KEY,
    question TEXT NOT NULL,
    possible_answers TEXT[] NOT NULL,
    correct_answer TEXT NOT NULL
);

INSERT INTO questions (question, possible_answers, correct_answer) VALUES
    ('"Long ago, the four nations lived together in harmony. Then, everything changed when ________ attacked."', 
     '{"the Water Tribes", "the Fire Nation", "the Earth Kingdom", "the Air Nomads"}',
     'the Fire Nation'),
    ('Aang becomes an airbending master at the young age of _____',
     '{"12", "6", "10", "16"}',
     '12'),
    ('How long is Aang frozen in ice?',
     '{"50 years", "20 years", "100 years", "250 years"}',
     '100 years'),
    ('What is the name of the Fire Nation prince tasked with finding the Avatar?',
     '{"Jet", "Haru", "Zuko", "Bumi"}',
     'Zuko'),
    ('Aang''s flying bison is named...?',
     '{"Momo", "Fang", "Appa", "Naga"}',
     'Appa'),
    ('What is Sokka''s signature weapon that he inherited from his father?',
     '{"A sword", "A machete", "A katana", "A boomerang"}',
     'A boomerang'),
    ('What is the name of the reigning Fire Lord?',
     '{"Roku", "Ozai", "Sozin", "Azulon"}',
     'Ozai'),
    ('The female warriors who fight using metal fans are the...?',
     '{"Freedom fighters", "Dai Li", "Kyoshi warriors", "White Lotus"}',
     'Kyoshi warriors'),
    ('Aang and Katara learn waterbending from Master _____?',
     '{"Pakku", "Yakone", "Arnook", "Unalaq"}',
     'Pakku'),
    ('Which spirit is the guardian of the library of knowledge?',
     '{"Wan", "Wan Shi Tong", "Koh", "Hei Bai"}',
     'Wan Shi Tong'),
    ('Which location is believed to be the birthplace of earthbending?',
     '{"Canal of Two Lovers", "Cave of Star Crossed Lovers", "Cave of Two Lovers", "Tunnel of Two Lovers"}',
     'Cave of Two Lovers'),
    ('Team Avatar adopts a flying lemur and names it...?',
     '{"Fang", "Momo", "Flopsie", "Appa"}',
     'Momo'),
    ('Which Avatar came right before Aang?',
     '{"Kiyoshi", "Kuruk", "Roku", "Korra"}',
     'Roku'),
    ('Bumi is the King of _______?',
     '{"Ba Sing Se", "Omashu", "Hou-Ting", "Garsai"}',
     'Omashu'),
    ('Admiral _____ was the leader of the Fire Nation Navy',
     '{"Zhao", "Kunyo", "Lu Ten", "Shyu"}',
     'Zhao'),
    ('Princess ____ becomes the new moon spirit',
     '{"Korra", "Hama", "Yuri", "Yue"}',
     'Yue'),
    ('Which two air temples exclusively housed female airbenders?',
     '{"Northern and Southern", "Southern and Eastern", "Western and Eastern", "Northern and Western"}',
     'Western and Eastern'),
    ('What once-in-a-century event increases firebenders'' power?',
     '{"Sozin''s comet", "Sozin''s sun", "Sozn''s meteor", "Sozin''s volcano"}',
     'Sozin''s comet'),
    ('Toph fights in underground earthbending tournaments under the name...?',
     '{"The Blind Boulder", "The Blind Bandit", "The Hippo", "Twinkle Toes"}',
     'The Blind Bandit'),
    ('What is the strongest ability that the Avatar can invoke?',
     '{"The Avatar Phase", "The Avatar''s Zenith", "Summoning dark spirits", "The Avatar State"}',
     'The Avatar State'),
    ('What is the capital of the Earth kingdom?',
     '{"Ba Sing Se", "Kaya''s town", "Kyoshi Island", "Yu Dao"}',
     'Ba Sing Se'),
    ('Zuko''s love interest (and one of his sister''s best friends) is named...?',
     '{"Ty Lee", "Suki", "Mai", "Ursa"}',
     'Mai'),
    ('The bounty hunter who rides on a shirshu is named...?',
     '{"Mai", "June", "Ty Lee", "Nyla"}',
     'June'),
    ('Who leads the Freedom Fighters?',
     '{"Haru", "Jet", "Suki", "Iroh"}',
     'Jet'),
    ('Who are the only known firebenders capable of generating lightning?',
     '{"Ozai, Azula, Iroh", "Azula, Iroh, Zuko", "Ozai, Azula, Zuko", "Sozin, Ozai, Iroh"}',
     'Ozai, Azula, Iroh'),
    ('What phrase makes Appa fly?',
     '{"Whoa", "Yip-yip", "Hiyah", "Up"}',
     'Yip-yip'),
    ('What is the name of the secret society Iroh belongs to?',
     '{"The Order of the Red Lotus", "The Order of the White Jasmine", "The Order of the White Lotus", "The Order of the White Rose"}',
     'The Order of the White Lotus'),
    ('Who teaches Aang firebending?',
     '{"Iroh", "Zuko", "Jeong Jeong", "Roku"}',
     'Zuko'),
    ('What dark skill can extremely advanced waterbenders do?',
     '{"Shoot lightning", "Summoning evil spirits", "Bloodbending", "Reading minds"}',
     'Bloodbending'),
    ('Toph creates the earthbending technique...?',
     '{"Bloodbending", "Energybending", "Lightningbending", "Metalbending"}',
     'Metalbending'),
    ('What does the Fire Lord rename himself once he takes over the world?',
     '{"Dark Lord", "High Councilor", "Phoenix King", "Supreme Leader"}',
     'Phoenix King'),
    ('The Earth kingdom''s secret police is called the...?',
     '{"Rough Rhinos", "Yuyan Archers", "Red Lotus", "Dai Li"}',
     'Dai Li'),
    ('Zuko and Azula''s mother is named...?',
     '{"Ty Lee", "Ursula", "Ursa", "Suki"}',
     'Ursa'),
    ('How does Aang defeat the Fire Lord?',
     '{"He banishes him to the spirit world", "He removes his firebending ability", "He puts him in a comatose state", "He kills him"}',
     'He removes his firebending ability'),
    ('Sokka and Katara are from the Water Tribe of the ____ Pole',
     '{"North", "South"}',
     'South');

